# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "litmos-client"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Kennon Ballou"]
  s.date = "2012-12-18"
  s.description = "Litmos-Client is a Ruby gem that provides a wrapper for interacting with the Litmos Learning Management System API."
  s.email = "kennon@angryturnip.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/litmos-client.rb",
    "lib/litmos_client.rb",
    "lib/litmos_client/courses.rb",
    "lib/litmos_client/teams.rb",
    "lib/litmos_client/users.rb",
    "litmos-client.gemspec",
    "test/helper.rb",
    "test/test_litmos_client.rb"
  ]
  s.homepage = "http://github.com/kennon/litmos-client"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "2.6.7"
  s.summary = "Litmos-client is a Ruby wrapper for the Litmos API"
  s.test_files = [
    "test/helper.rb",
    "test/test_litmos_client.rb"
  ]

  s.add_dependency "bundler"
  s.add_dependency "rake"
  s.add_dependency "jeweler"
  s.add_dependency "mocha"
  s.add_dependency "shoulda"
  s.add_dependency "rest-client"
  s.add_dependency "test-unit"
end
